apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cartservice
  namespace: otel
spec:
  endpoints:
    - interval: 60s
      port: 8080
  selector:
    matchLabels:
      app.kubernetes.io/component: cartservice