{
 "title": "Pod Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_labels, label_bop_app_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{label_bop_app_name=\"$app\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Readiness",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=\"$pod\"}) / sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Running\"}) * 100"
    }
   ]
  },
  {
   "title": "Historical Container Readiness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=\"$pod\"}) / sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Running\"}) * 100",
     "legendFormat": "Readiness"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=\"$pod\", phase=\"Running\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Pending\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Failed\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Historical Pods Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Running\"})",
     "legendFormat": "Runnning"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=\"$pod\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Historical Containers Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=\"$pod\"})",
     "legendFormat": "Runnning"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=\"$pod\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=\"$pod\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Memory Limit Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_failcnt{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_failures_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive PKGs Dropped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_packets_dropped_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Receive Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_errors_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send PKGs Dropped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_network_send_packets_dropped_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Send Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_network_send_errors_total{pod=\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod $pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\"}) / 1024"
    }
   ]
  },
  {
   "title": "Pod $pod CPU Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "-sum(rate(container_cpu_system_seconds_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Pod $pod Network I/O Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pod $pod Containers CPU Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(container_spec_cpu_quota{pod=\"$pod\"} - container_spec_cpu_shares{pod=\"$pod\"}) / container_spec_cpu_quota{pod=\"$pod\"} * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod $pod Containers CPU Throttle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=\"$pod\"}[$interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod $pod Containers Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(container_spec_memory_limit_bytes{pod=\"$pod\"} - container_memory_usage_bytes{pod=\"$pod\"}) / container_spec_memory_limit_bytes{pod=\"$pod\"} * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod $pod Containers Memory Limit Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_failcnt{pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}