---
sloth:
  app: frontend-new
  slos:
    - name: availability
      percentile: 98
      category: availability
      description: SLO
      custom_error_ratio_query: |
        (sum(increase(probe_recording_count:probe_success_failed:rate1d{instance="http://frontend:80", job="blackbox"}[{{"{{.window}}"}}]))
        /
        (sum(increase(probe_recording_count:count_total:rate1d{instance="http://frontend:80", job="blackbox"}[{{"{{.window}}"}}])) > 0)) OR on() vector(0)