---
sloth:
  app: frontend-new
  slos:
    - name: availability
      percentile: 98
      category: availability
      description: SLO
      custom_error_ratio_query: |
        (sum(increase(probe_recording_count:probe_success_failed:rate1d{instance="http://nginx:8080", job="blackbox"}[{{"{{.window}}"}}]))
        /
        (sum(increase(nginx_http_response_count_total{service="frontend"}[{{"{{.window}}"}}])) > 0)) OR on() vector(0)