apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johnbayo/sre.git
    targetRevision: HEAD
    path: ./configs/local/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: onlineboutique
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus
  url: https://prometheus-community.github.io/helm-charts
  type: helm
  