apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.12.0
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - ./configs/local/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: prometheus
#  namespace: onlineboutique
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: prometheus
#  url: https://prometheus-community.github.io/helm-charts
#  type: helm