apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: us-docker.pkg.dev/online-boutique-ci/charts
    chart: onlineboutique
    targetRevision: 0.9.0  
    helm:
      valueFiles:
        - $values/configs/local/onlineboutique/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/onlineboutique/
    ref: values
  - repoURL: git@github.com:johnbayo/sre.git
    path: kustomize-templates/onlineboutique/
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: onlineboutique
#  namespace: onlineboutique
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: onlineboutique
#  url: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique
#  type: helm
  