apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique
    chart: onlineboutique
    helm:
      releaseName: onlineboutique
      valueFiles:
        - values.yaml  # Assuming 'values.yaml' is part of your chart; adjust the path as necessary
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: onlineboutique
#  namespace: onlineboutique
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: onlineboutique
#  url: oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique
#  type: helm
  