apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: open-telemetry
    targetRevision: 0.29.0  
    helm:
      valueFiles:
        - $values/configs/local/otel/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/otel/
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

