apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.29.0  
    helm:
      releaseName: opentelemetry-demo
      valueFiles:
        - $values/configs/local/otel/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/otel/
    ref: values
  - repoURL: https://slok.github.io/sloth
    chart: sloth
    targetRevision: 0.7.0
    helm:
      releaseName: sloth
      valueFiles: 
        - values.yaml
  - repoURL: ://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 9.0.1
    helm:
      releaseName: prometheus-operator-crds
      valueFiles: 
        - values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    targetRevision: HEAD
    path: configs/local/slo/
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

