apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.29.0  
    helm:
      releaseName: opentelemetry-demo
      valueFiles:
        - $values/configs/local/otel/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/otel/
    ref: values
  - repoURL: https://slok.github.io/sloth
    chart: sloth
    targetRevision: 0.7.0
    helm:
      releaseName: sloth
      valueFiles: 
        - values.yaml
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.9.0
    helm:
      releaseName: kube-prometheus-stack
      valueFiles: 
        - values.yaml
      parameters:
        - name: prometheus.enabled
          value: 'false'
        - name: alertmanager.enabled
          value: 'false'
        - name: grafana.enabled
          value: 'false'
        - name: prometheus-windows-exporter.prometheus.monitor.enabled
          value: 'false'
        - name: nodeExporter-enabled
          value: 'false'
  - repoURL: git@github.com:johnbayo/sre.git
    targetRevision: HEAD
    path: configs/local/slo/
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

