apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.12.0
    chart: prometheus
    helm:
      releaseName: prometheus
      valueFiles:
        - $values/configs/local/prometheus/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/prometheus/
    ref: values
#  - repoURL: https://slok.github.io/sloth
#    chart: sloth
#    targetRevision: 0.7.0
#    helm:
#      releaseName: sloth
#      valueFiles: 
#        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true