apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.6.0
    chart: tempo
    helm:
      releaseName: tempo
      valueFiles:
        - $values/configs/local/tempo/values.yaml
  - repoURL: git@github.com:johnbayo/sre.git
    path: configs/local/tempo/
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true